version: '3'

services:
  desafio-luizalabs-db:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=desafio-luizalabs-db
  desafio-luizalabs-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - desafio-luizalabs-db
    environment:
      - DATABASE_URL=postgresql://docker:docker@desafio-luizalabs-db:5432/desafio-luizalabs-db?schema=public
      - JWT_SECRET=secret

